version: '3.4'

services:
  library:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LibraryConnection=Data Source=db;Initial Catalog=Library;Integrated Security=False;User ID=sa;Password=VerySecret2020!;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;

    ports:
      - "80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    expose:
     - "1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=VerySecret2020!