version: '3.4'

services:
  library:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LibraryConnection=Server=host.docker.internal;Database=Library;User ID=myUsername;Password=myPassword;MultipleActiveResultSets=true;

    ports:
      - 9100:80